---
title: "Accuracy map'matching over Salerno and Catania areas"
author:
- Federico Karagulian
date: "ultima versione `r format(Sys.time(), '%d %B %Y, %H:%M')`"
output:
  word_document: 
    reference_docx: word_style_FK.docx
  pdf_document: default
  html_document: default
  number_sections: true
  bookdown::word_document: default
---


## Accuracy Catania

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap = "**Figura 1.** Accuracy Catania"}


rm(list = ls())

library(RPostgreSQL)
library(readr)
library(lubridate)
library(threadr)
library(stringr)
library(ggplot2)
library(dplyr)
library(openair)
library(gsubfn)
library(mgsub)
library(data.table)


setwd("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data")

# loads the PostgreSQL driver
drv <- dbDriver("PostgreSQL")


conn_HAIG <- dbConnect(drv, dbname = "HAIG_Viasat_CT",
                       host = "10.0.0.1", port = 5432,       
                       user = "postgres", password = "superuser")

conn_HAIG <- dbConnect(drv, dbname = "HAIG_Viasat_CT",
                       host = "192.168.134.43", port = 5432,       
                       user = "postgres", password = "vaxcrio1")


setwd("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data")


###############################################################################
###############################################################################

## load accuracy data from DB
###  ACCURACY: ([length of the matched trajectory] / [length of the travelled distance (sum  delta progressives)])*100

# accuracy_2019_all = dbGetQuery(conn_HAIG, "
#                SELECT *
#                FROM public.accuracy_2019 
#                WHERE accuracy <= 150 
#                AND accuracy >= 140")


accuracy_2019_all = dbGetQuery(conn_HAIG, "
                                    SELECT *
                                    FROM accuracy_2019
                                    ")


# TRIP_ID <- "4482172_conc_87"
# 
# mapmatching = dbGetQuery(conn_HAIG, "
#                                     SELECT *
#                                     FROM mapmatching_2019
#                                     WHERE \"TRIP_ID\" = '4482172_conc_87'
#                                     ")
# 
# matched_candidates <- unique(mapmatching$idtrace)
# 
# routecheck = dbGetQuery(conn_HAIG, "
#                                     SELECT *
#                                     FROM routecheck_2019
#                                      WHERE \"TRIP_ID\" = '4482172_conc_87'
#                                     ")
# 
# matched_tracks <- unique(routecheck$id)


accuracy_2019_all <- accuracy_2019_all %>%
  filter(accuracy > 0 & accuracy <= 100)


accuracy_2019 = dbGetQuery(conn_HAIG, "
                                    SELECT accuracy
                                    FROM accuracy_2019
                                    ")

accuracy_2019$accuracy <- as.numeric(accuracy_2019$accuracy)


### summary STATS (80%-120% accuracy) #######################
#############################################################
grouped_accuracy <- accuracy_2019 %>%
  group_by(accuracy) %>%
  summarise(count = length(accuracy))
TOTAL = sum(grouped_accuracy$count)
good_interval <- grouped_accuracy %>%
  filter(accuracy >= 80 & accuracy <= 120)
GOODNESS_matching <- round((sum(good_interval$count) / TOTAL)*100 , digits = 2)
#############################################################
#############################################################


accuracy_2019 <- accuracy_2019 %>%
  filter(accuracy > 0 & accuracy <= 100)

df_accuracy_2019_CT <- accuracy_2019



### plot a distribution
p <- ggplot(accuracy_2019, aes(x = accuracy)) +
  geom_histogram(binwidth = 10) +  # 25
  # geom_histogram() +
  theme_bw() 
# p



### plot a distribution
p <- ggplot(accuracy_2019, aes(x = accuracy)) +
  geom_histogram(binwidth = 8, fill="lightblue") +  # 8
  # geom_histogram() +
  theme_bw() +
  # geom_density(stat = 'bin') +
  theme(legend.title=element_blank()) + 
  aes(y=stat(count)/sum(stat(count))) + 
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  theme( strip.text = element_text(size = 13)) +
  guides(fill=FALSE) +
  theme(axis.text.x=element_text(angle=0,hjust=0.5,vjust=1, size=16)) +
  theme(axis.text.x=element_text(size=16, colour = "black")) +
  theme(axis.title.x = element_text(face="bold", colour="black", size=16)) +
  xlab("accuracy (%) = length matched path / length travelled distance") +
  ylab("frequenza (%)") +
  xlim(0,100)+
  geom_vline(xintercept = 87, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 80, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 96, col="blue", lty=2, size=1) +
  geom_text(aes(x = 85 , y = 0.23 , label = "90%"), size = 5) +
  geom_text(aes(x = 77, y = 0.23 , label = "80%"), size = 5) +
  geom_text(aes(x = 100 , y = 0.23 , label = "100%"), size = 5) +
  theme(axis.title.y = element_text(face="bold", colour="black", size=16),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=16, colour="black")) +
  ggtitle("Accuracy map-matching 2019 Viasat - Catania") +
  theme(plot.title = element_text(lineheight=.8, face="bold", size = 16))
p


```


*<br/><br/>*
*<br/><br/>*


## Accuracy Salerno

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap = "**Figura 2.** Accuracy Salerno"}


#### check Salerno ######################################################

conn_HAIG <- dbConnect(drv, dbname = "HAIG_Viasat_SA",
                       host = "10.0.0.1", port = 5432,       
                       user = "postgres", password = "superuser")


setwd("D:/ENEA_CAS_WORK/SENTINEL/viasat_data")

###############################################################################
###############################################################################

## load accuracy data from DB
###  ACCURACY: ([length of the matched trajectory] / [length of the travelled distance (sum  delta progressives)])*100

accuracy_2019_all = dbGetQuery(conn_HAIG, "
                                    SELECT *
                                    FROM accuracy_2019
                                    ")

accuracy_2019 = dbGetQuery(conn_HAIG, "
                                    SELECT accuracy
                                    FROM accuracy_2019
                                    ")

accuracy_2019$accuracy <- as.numeric(accuracy_2019$accuracy)


### summary STATS (80%-120% accuracy) #######################
#############################################################
grouped_accuracy <- accuracy_2019 %>%
  group_by(accuracy) %>%
  summarise(count = length(accuracy))
TOTAL = sum(grouped_accuracy$count)
good_interval <- grouped_accuracy %>%
  filter(accuracy >= 80 & accuracy <= 120)
GOODNESS_matching <- round((sum(good_interval$count) / TOTAL)*100 , digits = 2)
#############################################################
#############################################################

accuracy_2019 <- accuracy_2019 %>%
  filter(accuracy > 0 & accuracy <= 100)


df_accuracy_2019_SA <- accuracy_2019


### plot a distribution
p <- ggplot(accuracy_2019, aes(x = accuracy)) +
  geom_histogram(binwidth = 10) +  # 25
  # geom_histogram() +
  theme_bw() 
# p



### plot a distribution
p <- ggplot(accuracy_2019, aes(x = accuracy)) +
  geom_histogram(binwidth = 8,  fill="orange") +  # 25   # 20
  # geom_histogram() +
  theme_bw() +
  # geom_density(stat = 'bin') +
  theme(legend.title=element_blank()) + 
  aes(y=stat(count)/sum(stat(count))) + 
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  theme( strip.text = element_text(size = 13)) +
  guides(fill=FALSE) +
  theme(axis.text.x=element_text(angle=0,hjust=0.5,vjust=1, size=12)) +
  theme(axis.text.x=element_text(size=12, colour = "black")) +
  theme(axis.title.x = element_text(face="bold", colour="black", size=13)) +
  xlab("accuracy (%) = length matched path / length travelled distance") +
  ylab("frequenza (%)") +
  ylim(0,0.3) +
  geom_vline(xintercept = 87, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 80, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 96, col="blue", lty=2, size=1) +
  geom_text(aes(x = 85 , y = 0.23 , label = "90%"), size = 5) +
  geom_text(aes(x = 77, y = 0.23 , label = "80%"), size = 5) +
  geom_text(aes(x = 100 , y = 0.23 , label = "100%"), size = 5) +
  theme(axis.title.y = element_text(face="bold", colour="black", size=13),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=13, colour="black")) +
  ggtitle("Accuracy map-matching 2019 Viasat - Salerno") +
  theme(plot.title = element_text(lineheight=.8, face="bold", size = 13))
p



```



*<br/><br/>*
*<br/><br/>*



````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap = "**Figura 3.** Accuracy Catania and Salerno"}


##############################################################################
##############################################################################

### join all ratios together....

names(df_accuracy_2019_CT) <- "accuracy"
df_accuracy_2019_CT$source <- "Catania"


names(df_accuracy_2019_SA) <- "accuracy"
df_accuracy_2019_SA$source <- "Salerno"


df <- rbind(df_accuracy_2019_CT, 
            df_accuracy_2019_SA)
somma_df <- df %>%
  group_by(source) %>%
  summarise(total = length(accuracy))

  
  
  p <- ggplot(df) + 
  aes(x =source, y = accuracy) +
  geom_boxplot(fill = "orange") + 
  theme_bw() +
  theme(axis.title.x = element_text(face="bold", colour="black", size=13),     
        axis.text.x=element_text(angle=0,hjust=0.5,vjust=1, size=14)) +
  ylab("frequenza (%)") +
  xlab("accuratezza") +
  theme(axis.title.y = element_text(face="bold", colour="black", size=13),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=13, colour="black")) +
  geom_text(data = somma_df, aes(x = source, y = 2, label = total), size = 4, hjust = 1.5,  vjust = -0.5)+
  ggtitle("accuratezza map-matching su Catania e Salerno") +
  theme(plot.title = element_text(lineheight=.8, face="bold", size = 13))
  p

###############################################################################
###############################################################################





```


*<br/><br/>*
*<br/><br/>*




## Accuracy Catania by LENGTH

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap = "**Figura 1a.** Accuracy Catania"}


setwd("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data")

### get all length (in meters) of matched path together with the sum of progressive lenght and the accuracy (%)

accuracy_2019_10_40 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_10_40_percent.csv",  
                                header = T, sep=",")[-1]

accuracy_2019_40_50 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_40_50_percent.csv",  
                                header = T, sep=",")[-1]

accuracy_2019_50_60 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_50_60_percent.csv",  
                                header = T, sep=",")[-1]

accuracy_2019_60_70 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_60_70_percent.csv",  
                                header = T, sep=",")[-1]

accuracy_2019_70_80 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_70_80_percent.csv",  
                                header = T, sep=",")[-1]

accuracy_2019_80_90 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_80_90_percent.csv",  
                                header = T, sep=",")[-1]

accuracy_2019_90_100 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_90_100_percent.csv",  
                                header = T, sep=",")[-1]
accuracy_2019_100_105 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_100_105_percent.csv",  
                                header = T, sep=",")[-1]
accuracy_2019_105_110 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_105_110_percent.csv",  
                                header = T, sep=",")[-1]
accuracy_2019_110_115 <- read.csv("D:/ENEA_CAS_WORK/Catania_RAFAEL/viasat_data/all_mapped_length_CATANIA_110_115_percent.csv",  
                                header = T, sep=",")[-1]
accuracy_2019_100_105$accuracy <- (accuracy_2019_100_105$accuracy - 10)
accuracy_2019_105_110$accuracy <- (accuracy_2019_105_110$accuracy - 10)
accuracy_2019_110_115$accuracy <- (accuracy_2019_110_115$accuracy - 10)
accuracy_2019_90_100 <- rbind(accuracy_2019_90_100, accuracy_2019_100_105, accuracy_2019_105_110, accuracy_2019_110_115)
 

###############################################################################
###############################################################################

# make 0 to 40.....
names(accuracy_2019_10_40) <- c("matched_distance", "progressive_distance", "accuracy %")
names(accuracy_2019_40_50) <- c("matched_distance", "progressive_distance", "accuracy %")
names(accuracy_2019_50_60) <- c("matched_distance", "progressive_distance", "accuracy %")
names(accuracy_2019_60_70) <- c("matched_distance", "progressive_distance", "accuracy %")
names(accuracy_2019_70_80) <- c("matched_distance", "progressive_distance", "accuracy %")
names(accuracy_2019_80_90) <- c("matched_distance", "progressive_distance", "accuracy %")
names(accuracy_2019_90_100) <- c("matched_distance", "progressive_distance", "accuracy %")


accuracy_2019 <- rbind(accuracy_2019_10_40,
                       accuracy_2019_40_50,
                       accuracy_2019_50_60,
                       accuracy_2019_60_70,
                       accuracy_2019_70_80,
                       accuracy_2019_80_90,
                       accuracy_2019_90_100)


accuracy_2019 <- accuracy_2019 %>%
  filter(matched_distance < 25000)


### plot a distribution
p <- ggplot(accuracy_2019, aes(x = matched_distance)) +
  theme_bw() +
  geom_density(stat = 'bin') +
  theme(legend.title=element_blank()) + 
  aes(y=stat(count)/sum(stat(count))) + 
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  theme( strip.text = element_text(size = 20)) +
  guides(fill=FALSE) +
  theme(axis.text.x=element_text(angle=0,hjust=0.5,vjust=1, size=20)) +
  theme(axis.text.x=element_text(size=20, colour = "black")) +
  theme(axis.title.x = element_text(face="bold", colour="black", size=20)) +
  xlab("matched distance (meters)") +
  ylab("frequency (%)") +
  # xlim(0,100)+
  # geom_vline(xintercept = 5200, col="blue", lty=2, size=1) +
  # geom_vline(xintercept = 700, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 700, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 2700, col="blue", lty=2, size=1) +
  geom_text(aes(x = 500 , y = 0.15 , label = "700 m"), size = 5) +
  geom_text(aes(x = 4000 , y = 0.15 , label = "2.7 km"), size = 5) +
  # geom_text(aes(x = 1000 , y = 0.15 , label = "1.5 km"), size = 4) +
  theme(axis.title.y = element_text(face="bold", colour="black", size=20),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=20, colour="black")) +
  ggtitle("Matched distance distribution - Catania") +
  theme(plot.title = element_text(lineheight=.8, face="bold", size = 20))
p




```


*<br/><br/>*
*<br/><br/>*



## Accuracy Catania by LENGTH

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap = "**Figura 1b.** Accuracy Catania"}


accuracy_2019 <- accuracy_2019 %>%
  filter(matched_distance > 1600)

### plot a distribution
p <- ggplot(accuracy_2019, aes(x = `accuracy %`)) +
  geom_histogram(binwidth = 8, fill="lightblue") +  # 8
  # geom_histogram() +
  theme_bw() +
  # geom_density(stat = 'bin') +
  theme(legend.title=element_blank()) + 
  aes(y=stat(count)/sum(stat(count))) + 
  scale_y_continuous(labels = scales::percent) +
  theme_bw() +
  theme( strip.text = element_text(size = 13)) +
  guides(fill=FALSE) +
  theme(axis.text.x=element_text(angle=0,hjust=0.5,vjust=1, size=16)) +
  theme(axis.text.x=element_text(size=16, colour = "black")) +
  theme(axis.title.x = element_text(face="bold", colour="black", size=16)) +
  xlab("accuracy (%) = length matched path / length travelled distance") +
  ylab("frequenza (%)") +
  xlim(0,100)+
  geom_vline(xintercept = 87, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 80, col="blue", lty=2, size=1) +
  geom_vline(xintercept = 96, col="blue", lty=2, size=1) +
  geom_text(aes(x = 85 , y = 0.23 , label = "90%"), size = 5) +
  geom_text(aes(x = 77, y = 0.23 , label = "80%"), size = 5) +
  geom_text(aes(x = 100 , y = 0.23 , label = "100%"), size = 5) +
  theme(axis.title.y = element_text(face="bold", colour="black", size=16),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=16, colour="black")) +
  ggtitle("Accuracy map-matching 2019 Viasat - Catania") +
  theme(plot.title = element_text(lineheight=.8, face="bold", size = 16))
p


```
