---
title: "Summary statistics CATANIA (RAFAEL)"
author:
- Federico Karagulian
date: "ultima versione `r format(Sys.time(), '%d %B %Y, %H:%M')`"
output:
  word_document: 
    reference_docx: word_style_FK.docx
  pdf_document: default
  html_document: default
  number_sections: true
  bookdown::word_document: default
---

*<br/><br/>*


````{r, message = FALSE, echo = FALSE, warning = FALSE}

rm(list = ls())

library(ggplot2)
library(stringr)
library(tidyr)
library(readr)
library(broom)
library(threadr)
library(dplyr)
library(dygraphs)
library(ggpmisc)
library(plotly)
library(GGally)
library(htmlwidgets)
library(htmltools)
library(webshot)
library(ggrepel)
library(openair)
library(widgetframe)
library(grid)
library(gridExtra)
library(pander)
library(varhandle)
options(scipen=5)
options(warn=-1)
library(RPostgreSQL)

setwd("D:/ENEA_CAS_WORK/Catania_RAFAEL")


# loads the PostgreSQL driver
drv <- dbDriver("PostgreSQL")

## connect to the Brescia PostgreSQL DB
conn_HAIG <- dbConnect(drv, dbname = "HAIG_Viasat_CT",
                       host = "10.0.0.1", port = 5432,       
                       user = "postgres", password = "superuser")


## check all available tables
# dbListTables(conn_HAIG)
## get fields names of tables in the DB
# dbListFields(conn_HAIG, "routecheck_2019")


start_time = Sys.time()

# get all trips ID
# all_TRIPS = dbGetQuery(conn_HAIG, "SELECT \"TRIP_ID\"
#                                    FROM routecheck_2019
#                                    group by \"TRIP_ID\"
#                                     ")
# write.csv(all_TRIPS, "D:/ENEA_CAS_WORK/Catania_RAFAEL/all_TRIPS.CATANIA.csv")
all_TRIPS <- read_csv("all_TRIPS.CATANIA.csv")[-1]

# all_TRIPS = dbGetQuery(conn_HAIG, "SELECT \"TRIP_ID\"
#                                    FROM routecheck_2019
#                                    WHERE idterm = '5440008'
#                                    group by \"TRIP_ID\"
#                                     ")


# BBB = dbGetQuery(conn_HAIG, "SELECT * FROM routecheck_2019
#                                    WHERE idterm = '5440008' and idtrajectory = '62215211' and speed > 30 
#                                     ")

stop_time = Sys.time()
diff <- (stop_time - start_time)
diff

## make a list of unique TRIP_ID
list_all_TRIPS <- unique(all_TRIPS$TRIP_ID) 
length(list_all_TRIPS)
## SELECT only concatenated TRIPS
list_TRIPS_conc <- grep("_conc_", list_all_TRIPS)
length(list_TRIPS_conc)
(length(list_TRIPS_conc)/length(list_all_TRIPS))*100 ###(87%)


````


## ((((aggiungere se non complicato la percentuale di viaggi concatenati sul totale))))))) .

## ((((((Puoi aggiungere qualche statistica su percorrenze medie (lunghezza viaggio) e numero di viaggi, velocità medie (dei viaggi) anche in formato grafico (distribuzioni)))))))))  ## use routecheck_2019  and route_2019 (percorrenza media per numero d viaggi)

## ((((E’ disponibile la mappa dei sensori fissi??))))))  ##OK


*<br/><br/>*



````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 0.** Distribuzione delle velocita' istantanee su Catania (Febbraio, Maggio, Agosto, Novembre 2019)"}


## tripdistance_m (in meters)
## triptime_s (in seconds)

########### ------------------------------ ########
#### data from Giancarlo Giuli ####################
###################################################

### Load all trips

data_GG <- read_csv("df_Viag_0_26541.csv")[-1]
data_GG <- data_GG %>%
  select(Id_Term,
         Id_Viaggi,
         Veh_Type,
         O_Data,
         D_Sosta_Dur,
         Viag_Km,
         Viag_Durata)
data_GG$speed_trip = (data_GG$Viag_Km)/(data_GG$Viag_Durata)  ## km/h
data_GG$hour <- hour(data_GG$O_Data)
data_GG$day <- weekdays(as.Date(data_GG$O_Data))
data_GG$month <- month(as.Date(data_GG$O_Data))
### rename data
data_GG$Veh_Type <- gsub(1, "auto", (data_GG$Veh_Type))
data_GG$Veh_Type <- gsub(2, "veicoli commerciali", (data_GG$Veh_Type))
## rename columns
colnames(data_GG)[colnames(data_GG) == 'Veh_Type'] <- 'vehtype'
colnames(data_GG)[colnames(data_GG) == 'Id_Term'] <- 'idterm'


trips <- data_GG %>%
  filter(Viag_Km > 0 & Viag_Km < 150 &
           Viag_Durata > 0.01600 & Viag_Durata < 5 & 
         speed_trip < 150 & speed_trip > 15) 


# ## quick check
# ## travelled distance
# ggplot(data_copy, aes(Viag_Km)) +
# geom_density()
# 
# ## trip time
# ggplot(data_copy, aes(Viag_Durata)) +
# geom_density()
# 
# ## speed
# ggplot(data_copy, aes(speed_trip)) +
# geom_density()


#######################
### Velocita' #########
### ----------- #######

#### Istogramma tutti i viaggi con velocità media con intervalli di 20km/h tutti i veicoli

### auto ###
BBB <- NULL
bin_speed = seq(from = 0, to = 180, by =10)

for (i in 1:length(bin_speed)){
  #i=5
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "auto") %>%
      filter(speed_trip <= bin_speed[i])  %>%
      summarise(counts = length(idterm))
  }else{
    AAA <- trips %>%
       filter(vehtype == "auto") %>%
      filter(speed_trip <= bin_speed[i] & speed_trip >= bin_speed[i-1]) %>%
      summarise(counts = length(idterm))
   
  }
  BBB<- rbind(BBB, AAA)
  
}

passaggi_20kmh_auto <- as.data.frame(cbind(bin_speed, BBB))
passaggi_20kmh_auto <- na.omit(passaggi_20kmh_auto)
passaggi_20kmh_auto$vehtype <- "auto"


### veicoli commerciali ###
BBB <- NULL
bin_speed = seq(from = 0, to = 180, by =10)

for (i in 1:length(bin_speed)){
  #i=5
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "veicoli commerciali") %>%
      filter(speed_trip <= bin_speed[i])  %>%
      summarise(counts = length(idterm))
  }else{
    AAA <- trips %>%
       filter(vehtype == "veicoli commerciali") %>%
      filter(speed_trip <= bin_speed[i] & speed_trip >= bin_speed[i-1]) %>%
      summarise(counts = length(idterm))
   
  }
  BBB<- rbind(BBB, AAA)
  
}

passaggi_20kmh_commerciali <- as.data.frame(cbind(bin_speed, BBB))
passaggi_20kmh_commerciali <- na.omit(passaggi_20kmh_commerciali)
passaggi_20kmh_commerciali$vehtype <- "veicoli commerciali"

passaggi_20kmh <- rbind(passaggi_20kmh_auto,
                        passaggi_20kmh_commerciali)


## plot
passaggi_20kmh$bin_speed <- as.factor(passaggi_20kmh$bin_speed)
passaggi_20kmh_auto$bin_speed <- as.factor(passaggi_20kmh_auto$bin_speed)

p <- ggplot(data = passaggi_20kmh,
              aes(bin_speed, counts, fill = bin_speed)) + guides(fill=FALSE) +
    geom_bar(stat = "identity") + 
    guides(fill=FALSE) +
   # facet_wrap(~vehtype) +
    # ylim(0, 90) +
    theme_bw() +
    theme( strip.text = element_text(size = 13)) +
    theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
    theme(axis.text.x=element_text(size=13,face="bold", colour = "black")) +
    theme(axis.title.x = element_blank()) +                  # Remove x-axis label
    ylab("numero di viaggi") +            # Set y-axis label
    xlab(expression(paste("velocità (km / h)"))) +
    theme(axis.title.y = element_text(face="bold", colour="black", size=10),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=9)) +
    theme(axis.title.x = element_text(face="bold", colour="black", size=13),
          axis.text.x  = element_text(angle=0, vjust=0.5, size=13, hjust = 0.5)) + 
    theme(axis.title.y = element_text(face="bold", colour="black", size=13),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=13)) +
    # scale_x_continuous(breaks=c(0, 5, 10, 15, 20)) +
    ggtitle("Numero di viaggi a velocità media ad intevalli di 10km/h GG") + 
    theme(plot.title = element_text(lineheight=.8, face="bold"))
  p

  
  
````
  
*<br/><br/>*

  
````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 1.** Distribuzione percentuale delle velocità medie di viaggio su Catania ad intevalli di 10 km/h (Febbraio, Maggio, Agosto, Novembre 2019)"}
  

###############################################################
###############################################################

### load all TRIPS

# data_FK = dbGetQuery(conn_HAIG, "SELECT route_2019.idtrajectory,
#                                      route_2019.tripdistance_m,
#                                      route_2019.triptime_s,
#                                      route_2019.timedate_o,
#                                      idterm_portata.idterm, idterm_portata.vehtype
#                                     FROM route_2019
#                                   LEFT JOIN idterm_portata
#                                    ON route_2019.idterm = idterm_portata.idterm  
#                                     ")
# write_csv(data_FK, "route_CATANIA.csv")

data_FK <- read_csv("route_CATANIA.csv")
## get month
data_FK$month <- month(as.Date(data_FK$timedate_o))

## shift time (UTC zones)
data_FK_Feb_Nov <- data_FK %>%
  filter(month %in% c(2,11)) %>%
  mutate(timedate_o = timedate_o - hours(1))

data_FK_May_Aug <- data_FK %>%
  filter(month %in% c(5,8)) %>%
  mutate(timedate_o = timedate_o + hours(0))
data_FK <- rbind(data_FK_Feb_Nov, data_FK_May_Aug)


## rename data
data_FK$vehtype <- gsub(1, "auto", (data_FK$vehtype))
data_FK$vehtype <- gsub(2, "veicoli commerciali", (data_FK$vehtype))
data_FK$speed_trip = (data_FK$tripdistance_m/1000)/(data_FK$triptime_s/3600)  ## km/h
data_FK$hour <- hour(data_FK$timedate_o)
data_FK$day <- weekdays(as.Date(data_FK$timedate_o))
data_FK$month <- month(as.Date(data_FK$timedate_o))
data_FK <- data_FK %>%
  filter(month %in% c(2,5,8,11))



trips <- data_FK %>%
  filter(tripdistance_m > 0 & tripdistance_m < 150000 &
           triptime_s > 60 & triptime_s < 20500 & 
         speed_trip < 150 & speed_trip > 15) 

# ## quick check -----------------------
# ## travelled distance
# ggplot(data_copy, aes(tripdistance_m)) +
# geom_density()
# 
# ## trip time
# ggplot(data_copy, aes(triptime_s)) +
# geom_density()
# 
# ## speed
# ggplot(data_copy, aes(speed_trip)) +
# geom_density()



# plots <- lapply(split(AAA, AAA$vehtype),FUN=function(speed_dist){ 
#     # ggplot(aes((speed), fill = as.factor(vehtype))) +
#     ggplot(speed_dist, aes(speed_trip)) +
#     # ggplot(aes( (mean_speed))) + 
#     geom_density(alpha = 0.5) +
#     # ylim(0, 0.035) +
#     # geom_histogram(binwidth=.05) +   ### counts
#     stat_function(fun = dnorm, 
#                   args = list(mean = mean(speed_dist$speed_trip),
#                            sd = sd(speed_dist$speed_trip)), colour = "red") +  ## fit           withGaussian
#     theme_bw() +
#     # geom_line(aes(y = pois), col = "blue") + 
#     # geom_line(aes(y = nbinom), col = "green") + 
#     theme(axis.title.x = element_text(face="bold", colour="black", size=13),     
#           axis.text.x=element_text(angle=0,hjust=0.5,vjust=0.5, size=12)) +
#     ylab("densità") +
#     xlab("velocità (km/h)") +
#     theme(axis.title.y = element_text(face="bold", colour="black", size=13),
#           axis.text.y  = element_text(angle=0, vjust=0.5, size=13, colour="black")) +
#     geom_vline(xintercept=mean(speed_dist$speed_trip), color="red", linetype="dashed", size=0.5) 
# })


# # Finally, present the plots on 2 columns.
# grid.arrange(plots$auto, plots$`veicoli commerciali`, nrow=1, ncol = 2, top = textGrob("        auto  veicoli pesanti",gp=gpar(fontsize=20,font=3)))



#######################
### Velocita' #########
### ----------- #######

#### Istogramma tutti i viaggi con velocità media con intervalli di 10km/h tutti i veicoli

### auto ###
BBB <- NULL
bin_speed = seq(from = 0, to = 140, by =10)

for (i in 1:length(bin_speed)){
  #i=5
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "auto") %>%
      filter(speed_trip <= bin_speed[i])  %>%
      summarise(counts = length(idtrajectory))
  }else{
    AAA <- trips %>%
       filter(vehtype == "auto") %>%
      filter(speed_trip <= bin_speed[i] & speed_trip >= bin_speed[i-1]) %>%
      summarise(counts = length(idtrajectory))
   
  }
  BBB<- rbind(BBB, AAA)
  
}

viaggi_10kmh_auto <- as.data.frame(cbind(bin_speed, BBB))
viaggi_10kmh_auto <- na.omit(viaggi_10kmh_auto)
viaggi_10kmh_auto$vehtype <- "auto"
viaggi_10kmh_auto$N_tot_trips <- sum(viaggi_10kmh_auto$counts)


### veicoli commerciali ###
BBB <- NULL
bin_speed = seq(from = 0, to = 140, by =10)

for (i in 1:length(bin_speed)){
  #i=5
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "veicoli commerciali") %>%
      filter(speed_trip <= bin_speed[i])  %>%
      summarise(counts = length(idtrajectory))
  }else{
    AAA <- trips %>%
       filter(vehtype == "veicoli commerciali") %>%
      filter(speed_trip <= bin_speed[i] & speed_trip >= bin_speed[i-1]) %>%
      summarise(counts = length(idtrajectory))
   
  }
  BBB<- rbind(BBB, AAA)
  
}

viaggi_10kmh_commerciali <- as.data.frame(cbind(bin_speed, BBB))
viaggi_10kmh_commerciali <- na.omit(viaggi_10kmh_commerciali)
viaggi_10kmh_commerciali$vehtype <- "veicoli commerciali"
viaggi_10kmh_commerciali$N_tot_trips <- sum(viaggi_10kmh_commerciali$counts)

viaggi_10kmh <- rbind(viaggi_10kmh_auto,
                        viaggi_10kmh_commerciali)
## calculate percentage of trips by vehtype
viaggi_10kmh$perc_count <- round((viaggi_10kmh$counts/viaggi_10kmh$N_tot_trips)*100, digits = 1)



## plot
viaggi_10kmh$bin_speed <- as.factor(viaggi_10kmh$bin_speed)

p <- ggplot(data = viaggi_10kmh,
              aes(bin_speed, perc_count, fill = bin_speed)) + guides(fill=FALSE) +
    geom_bar(stat = "identity") + 
    guides(fill=FALSE) +
    facet_wrap(~vehtype) +
    # ylim(0, 90) +
    theme_bw() +
    theme( strip.text = element_text(size = 15)) +
    theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
    theme(axis.text.x=element_text(size=13,face="bold", colour = "black")) +
    theme(axis.title.x = element_blank()) +                  # Remove x-axis label
    ylab("(%)") +            # Set y-axis label
    xlab(expression(paste("velocità (km/h)"))) +
    theme(axis.title.y = element_text(face="bold", colour="black", size=15),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=15)) +
    theme(axis.title.x = element_text(face="bold", colour="black", size=13),
          axis.text.x  = element_text(angle=0, vjust=0.5, size=10, hjust = 0.5)) + 
    # scale_x_continuous(breaks=c(0, 5, 10, 15, 20)) +
    ggtitle("Percentuale di viaggi in funzione della velocità media di viaggio") + 
    theme(plot.title = element_text(lineheight=.8, face="bold"))
  p


````

*<br/><br/>*


````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 2.** Percentuale distanza totale percorsa per giorno della settimana."}


## summary statistics by DAY of the WEEK #############
## assign name to month
trips$month <- as.factor(trips$month)
trips$month <- gsub(2, "febbraio", (trips$month))
trips$month <- gsub(5, "maggio", (trips$month))
trips$month <- gsub(8, "agosto", (trips$month))
trips$month <- gsub(11, "novembre", (trips$month))



trips_weekdays <- trips %>%
  group_by(month, day) %>%
  summarise(count = length(idtrajectory),
            total_km = sum(tripdistance_m/1000)) 

## find the number of trip travelled each months and their distance
trips_month <- trips %>%
  group_by(month) %>%
  summarise(N_trip_month = length(idtrajectory),
            total_km_month = sum(tripdistance_m/1000))



## merge above data
trips_weekdays <- trips_weekdays %>%
  left_join(trips_month, by = c("month"))

trips_weekdays <- trips_weekdays %>%
  group_by(month, day) %>%
  summarise(perc_count = round( (count/N_trip_month)*100, digits = 1 ),
            perc_km = round( (total_km/total_km_month)*100, digits = 1 )) 


trips_weekdays <- as.data.frame(trips_weekdays)
categories <- c("lunedì", "martedì", "mercoledì", "giovedì", "venerdì" ,"sabato" ,"domenica")

p <- ggplot(data = trips_weekdays,
            aes(day, perc_km, fill = day)) + guides(fill=FALSE) +
  geom_bar(stat="identity") +
  facet_wrap( ~ month, scales = "free_y") +
  guides(fill=FALSE) +
  scale_x_discrete(limits = categories) +
  ylim(0, 20) +
  theme_bw() +
  theme( strip.text = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
  theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
  theme(axis.title.x = element_blank()) +                  # Remove x-axis label
  ylab("(%)") +            # Set y-axis label
  theme(axis.title.y = element_text(face="bold", colour="black", size=14),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
  xlab("") +            # Set y-axis label
  theme(axis.title.x = element_text(face="bold", colour="black", size=14),
        axis.text.x  = element_text(angle=45, vjust=1, size=14)) +
  # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
  ggtitle("Percentuale della distanza percorsa per giorno della settimana") + 
  theme(plot.title = element_text(lineheight=.8, face="bold"))
p


````


*<br/><br/>*



````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 4.** Numero di viaggi per giorno della settimana."}


## summary statistics by DAY of the WEEK #############

p <- ggplot(data = trips_weekdays,
            aes(day, perc_count, fill = day)) + guides(fill=FALSE) +
  geom_bar(stat="identity") +
  facet_wrap( ~ month, scales = "free_y") +
  guides(fill=FALSE) +
  scale_x_discrete(limits = categories) +
  ylim(0, 20) +
  theme_bw() +
  theme( strip.text = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
  theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
  theme(axis.title.x = element_blank()) +                  # Remove x-axis label
  ylab("(%)") +            # Set y-axis label
  theme(axis.title.y = element_text(face="bold", colour="black", size=14),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
  xlab("") +            # Set y-axis label
  theme(axis.title.x = element_text(face="bold", colour="black", size=14),
        axis.text.x  = element_text(angle=45, vjust=1, size=14)) +
  # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
  ggtitle("Percentuale di viaggi per giorno della settimana") + 
  theme(plot.title = element_text(lineheight=.8, face="bold"))
p

````


*<br/><br/>*

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 3.** Distanza media per viaggio per giorni della settimana."}


## summary statistics by DAY of the WEEK #############

trips_weekdays <- trips %>%
  group_by(month, day) %>%
  summarise(count = length(idtrajectory),
            total_km = mean(tripdistance_m/1000, na.rm = T)) 

trips_weekdays <- as.data.frame(trips_weekdays)
categories <- c("lunedì", "martedì", "mercoledì", "giovedì", "venerdì" ,"sabato" ,"domenica")

p <- ggplot(data = trips_weekdays,
            aes(day, total_km, fill = day)) + guides(fill=FALSE) +
  geom_bar(stat="identity") +
  facet_wrap( ~ month, scales = "free_y") +
  guides(fill=FALSE) +
  scale_x_discrete(limits = categories) +
  ylim(0, 12) +
  theme_bw() +
  theme( strip.text = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
  theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
  theme(axis.title.x = element_blank()) +                  # Remove x-axis label
  ylab("(km percorsi)") +            # Set y-axis label
  theme(axis.title.y = element_text(face="bold", colour="black", size=14),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
  xlab("") +            # Set y-axis label
  theme(axis.title.x = element_text(face="bold", colour="black", size=14),
        axis.text.x  = element_text(angle=45, vjust=1, size=14)) +
  # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
  geom_hline(yintercept = 10, col="blue", lty=2, size=1) +
  ggtitle("Distanza media per viaggio e per giorno della settimana") + 
  theme(plot.title = element_text(lineheight=.8, face="bold"))
p


````


*<br/><br/>*



````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 5.** percentuale viaggi percorsi per ora della giornata."}


#### elaborations from Federico Karagulian #####

### summary statistics by HOUR
### find the number trips for each hour and travelled distance
trips_hour <- trips %>%
  group_by(month, hour) %>%
  summarise(count = length(idtrajectory),
            total_km = sum(tripdistance_m/1000)) 


## find the number of trip travelled each months and their distance
trips_month <- trips %>%
  group_by(month) %>%
  summarise(N_trip_month = length(idtrajectory),
            total_km_month = sum(tripdistance_m/1000))


## merge above data
trips_hour <- trips_hour %>%
  left_join(trips_month, by = c("month"))


trips_hour <- trips_hour %>%
  group_by(month, hour) %>%
  summarise(perc_count = round( (count/N_trip_month)*100, digits = 1 ),
            perc_km = round( (total_km/total_km_month)*100, digits = 1 )) 


trips_hour <- as.data.frame(trips_hour)


p <- ggplot(data = trips_hour,
              aes(hour, perc_count, fill = hour)) + guides(fill=FALSE) +
    geom_bar(stat = "identity") + 
    facet_wrap( ~ month, scales = "free_y") +
    guides(fill=FALSE) +
    ylim(0, 10) +
    theme_bw() +
    theme( strip.text = element_text(size = 15)) +
    theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
    theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
    theme(axis.title.x = element_blank()) +                  # Remove x-axis label
    ylab("(%)") +            # Set y-axis label
    theme(axis.title.y = element_text(face="bold", colour="black", size=14),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
    xlab("") +            # Set y-axis label
    theme(axis.title.x = element_text(face="bold", colour="black", size=12),
          axis.text.x  = element_text(angle=90, vjust=0.5, hjust=0.5, size=9)) +
    scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23)) +
    # scale_x_continuous(breaks=c(5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23)) +
    # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
    ggtitle("Percentuale di viaggi percorsi per ora della giornata") + 
    theme(plot.title = element_text(lineheight=.8, face="bold"))
p



````

*<br/><br/>*


````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 6.** percentuale della distanza percorsa per ora della giornata."}


p <- ggplot(data = trips_hour,
              aes(hour, perc_km, fill = hour)) + guides(fill=FALSE) +
    geom_bar(stat = "identity") + 
    facet_wrap( ~ month, scales = "free_y") +
    guides(fill=FALSE) +
    ylim(0, 10) +
    theme_bw() +
    theme( strip.text = element_text(size = 15)) +
    theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
    theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
    theme(axis.title.x = element_blank()) +                  # Remove x-axis label
    ylab("(%)") +            # Set y-axis label
    theme(axis.title.y = element_text(face="bold", colour="black", size=14),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
    xlab("") +            # Set y-axis label
    theme(axis.title.x = element_text(face="bold", colour="black", size=12),
          axis.text.x  = element_text(angle=90, vjust=0.5, hjust=0.5, size=9)) +
    scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23)) +
    # scale_x_continuous(breaks=c(5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23)) +
    # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
    ggtitle("Distanza percentuale percorsa per ora della giornata") + 
    theme(plot.title = element_text(lineheight=.8, face="bold"))
p


````


*<br/><br/>*

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 7.** Numero di viaggi per durata temporale (2 min)."}

## summary statistics for stop time #############


############################
### tempi di sosta #########
### ----------- ############

#### Istogramma di tutti i viaggi con tempi di sosta ad intervalli di 2 minuti

## convert stop time into minutes
trips <- as.data.frame(trips)
trips$triptime_min <- (trips$triptime_s)/60


### auto ###
BBB <- NULL
bin_stop = seq(from = 0, to = 80, by = 2)   ## max 2 ore trip = 120 minutes (2 hour trip)

for (i in 1:length(bin_stop)){
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "auto") %>%
      filter(triptime_min <= bin_stop[i])  %>%
      summarise(counts = length(idtrajectory))
  }else{
    AAA <- trips %>%
       filter(vehtype == "auto") %>%
      filter(triptime_min <= bin_stop[i] & triptime_min >= bin_stop[i-1]) %>%
      summarise(counts = length(idtrajectory))
   
  }
  BBB<- rbind(BBB, AAA)
  
}

viaggi_5min_auto <- as.data.frame(cbind(bin_stop, BBB))
viaggi_5min_auto <- na.omit(viaggi_5min_auto)
viaggi_5min_auto$vehtype <- "auto"
viaggi_5min_auto$N_tot_trips <- sum(viaggi_5min_auto$counts)



### veicoli commerciali ###
BBB <- NULL
bin_stop = seq(from = 0, to = 80, by = 2)   ## max 2 ore trip = 120 minutes (2 hour trip)


for (i in 1:length(bin_stop)){
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "veicoli commerciali") %>%
      filter(triptime_min <= bin_stop[i])  %>%
      summarise(counts = length(idtrajectory))
  }else{
    AAA <- trips %>%
       filter(vehtype == "veicoli commerciali") %>%
      filter(triptime_min <= bin_stop[i] & triptime_min >= bin_stop[i-1]) %>%
      summarise(counts = length(idtrajectory))
   
  }
  BBB<- rbind(BBB, AAA)
  
}


viaggi_5min_commerciali <- as.data.frame(cbind(bin_stop, BBB))
viaggi_5min_commerciali <- na.omit(viaggi_5min_commerciali)
viaggi_5min_commerciali$vehtype <- "veicoli commerciali"
viaggi_5min_commerciali$N_tot_trips <- sum(viaggi_5min_commerciali$counts)

viaggi_5min <- rbind(viaggi_5min_auto,
                        viaggi_5min_commerciali)
## calculate percentage of trips by vehtype
viaggi_5min$perc_count <- round((viaggi_5min$counts/viaggi_5min$N_tot_trips)*100, digits = 1)


## plot
viaggi_5min$bin_stop <- as.factor(viaggi_5min$bin_stop)
viaggi_5min$bin_stop <- as.numeric(viaggi_5min$bin_stop)

p <- ggplot(data = viaggi_5min,
              aes(bin_stop, perc_count, fill = bin_stop)) + guides(fill=FALSE) +
    geom_bar(stat = "identity") + 
    guides(fill=FALSE) +
    facet_wrap(~vehtype) +
    # ylim(0, 15) +
    theme_bw() +
    theme( strip.text = element_text(size = 15)) +
    theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
    theme(axis.text.x=element_text(size=13,face="bold", colour = "black")) +
    theme(axis.title.x = element_blank()) +                  # Remove x-axis label
    ylab("(%)") +            # Set y-axis label
    xlab(expression(paste("tempo di sosta (minuti)"))) +
    theme(axis.title.x = element_text(face="bold", colour="black", size=16),
          axis.text.x  = element_text(angle=0, vjust=0.5, size=16, hjust = 0.5)) + 
    theme(axis.title.y = element_text(face="bold", colour="black", size=20),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=20)) +
    # scale_x_continuous(breaks=c(0, 5, 10, 15, 20)) +
    ggtitle("Percentuale di viaggi per durata temporale") + 
   scale_x_continuous(breaks=c(4,8,12,16,20,24,28,32,36,40,44,48,52,56,60,64,68,72,76,80)) +
    theme(plot.title = element_text(lineheight=.8, face="bold"))
  p


````


*<br/><br/>*


````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 8.** Numero di viaggi per durata temporale (5 min)."}

## summary statistics for stop time #############


############################
### tempi di sosta #########
### ----------- ############

#### Istogramma di tutti i viaggi con tempi di sosta ad intervalli di 5 minuti

## convert stop time into minutes
trips <- as.data.frame(trips)
trips$triptime_min <- (trips$triptime_s)/60


### auto ###
BBB <- NULL
bin_stop = seq(from = 0, to = 80, by = 5)   ## max 2 ore trip = 120 minutes (2 hour trip)

for (i in 1:length(bin_stop)){
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "auto") %>%
      filter(triptime_min <= bin_stop[i])  %>%
      summarise(counts = length(idtrajectory))
  }else{
    AAA <- trips %>%
       filter(vehtype == "auto") %>%
      filter(triptime_min <= bin_stop[i] & triptime_min >= bin_stop[i-1]) %>%
      summarise(counts = length(idtrajectory))
   
  }
  BBB<- rbind(BBB, AAA)
  
}

viaggi_5min_auto <- as.data.frame(cbind(bin_stop, BBB))
viaggi_5min_auto <- na.omit(viaggi_5min_auto)
viaggi_5min_auto$vehtype <- "auto"
viaggi_5min_auto$N_tot_trips <- sum(viaggi_5min_auto$counts)


### veicoli commerciali ###
BBB <- NULL
bin_stop = seq(from = 0, to = 80, by = 5)   ## max 2 ore trip = 120 minutes (2 hour trip)


for (i in 1:length(bin_stop)){
  if (i==1){
    AAA <- trips %>%
      filter(vehtype == "veicoli commerciali") %>%
      filter(triptime_min <= bin_stop[i])  %>%
      summarise(counts = length(idtrajectory))
  }else{
    AAA <- trips %>%
       filter(vehtype == "veicoli commerciali") %>%
      filter(triptime_min <= bin_stop[i] & triptime_min >= bin_stop[i-1]) %>%
      summarise(counts = length(idtrajectory))
   
  }
  BBB<- rbind(BBB, AAA)
  
}

viaggi_5min_commerciali <- as.data.frame(cbind(bin_stop, BBB))
viaggi_5min_commerciali <- na.omit(viaggi_5min_commerciali)
viaggi_5min_commerciali$vehtype <- "veicoli commerciali"
viaggi_5min_commerciali$N_tot_trips <- sum(viaggi_5min_commerciali$counts)

viaggi_5min <- rbind(viaggi_5min_auto,
                        viaggi_5min_commerciali)
## calculate percentage of trips
## calculate percentage of trips by vehtype
viaggi_5min$perc_count <- round((viaggi_5min$counts/viaggi_5min$N_tot_trips)*100, digits = 1)



## plot
viaggi_5min$bin_stop <- as.factor(viaggi_5min$bin_stop)

p <- ggplot(data = viaggi_5min,
              aes(bin_stop, perc_count, fill = bin_stop)) + guides(fill=FALSE) +
    geom_bar(stat = "identity") + 
    guides(fill=FALSE) +
    facet_wrap(~vehtype) +
    ylim(0, 30) +
    theme_bw() +
    theme( strip.text = element_text(size = 15)) +
    theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
    theme(axis.text.x=element_text(size=13,face="bold", colour = "black")) +
    theme(axis.title.x = element_blank()) +                  # Remove x-axis label
    ylab("(%)") +            # Set y-axis label
    xlab(expression(paste("tempo di sosta (minuti)"))) +
    theme(axis.title.x = element_text(face="bold", colour="black", size=13),
          axis.text.x  = element_text(angle=0, vjust=0.5, size=10, hjust = 0.5)) + 
    theme(axis.title.y = element_text(face="bold", colour="black", size=14),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
    # scale_x_continuous(breaks=c(0, 5, 10, 15, 20)) +
    ggtitle("Percentuale di viaggi per durata temporale") + 
    theme(plot.title = element_text(lineheight=.8, face="bold"))
  p


````

*<br/><br/>*
*<br/><br/>*
*<br/><br/>*
*<br/><br/>*
*<br/><br/>*
*<br/><br/>*
*<br/><br/>*
*<br/><br/>*

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 9.** Tempo medio di viaggio per giorno della settimana."}


## summary statistics by DAY of the WEEK #############
### duration of the trip by day of the week ##########


triptime_weekdays <- trips %>%
  group_by(month, day) %>%
  summarise(mean_trip_time = mean(triptime_min, na.rm = T)) 


triptime_weekdays <- as.data.frame(triptime_weekdays)
categories <- c("lunedì", "martedì", "mercoledì", "giovedì", "venerdì" ,"sabato" ,"domenica")

p <- ggplot(data = triptime_weekdays,
            aes(day, mean_trip_time, fill = day)) + guides(fill=FALSE) +
  geom_bar(stat="identity") +
  facet_wrap( ~ month, scales = "free_y") +
  guides(fill=FALSE) +
  scale_x_discrete(limits = categories) +
  ylim(0, 20) +
  theme_bw() +
  theme( strip.text = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
  theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
  theme(axis.title.x = element_blank()) +                  # Remove x-axis label
  ylab("minuti") +            # Set y-axis label
  theme(axis.title.y = element_text(face="bold", colour="black", size=14),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
  xlab("") +            # Set y-axis label
  theme(axis.title.x = element_text(face="bold", colour="black", size=14),
        axis.text.x  = element_text(angle=45, vjust=1, size=14)) +
  # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
  geom_hline(yintercept = 15, col="black", lty=2, size=1) +
  ggtitle("tempo medio di viaggio per giorno della settimana") + 
  theme(plot.title = element_text(lineheight=.8, face="bold"))
p


````



*<br/><br/>*


````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 9.** Tempo medio di viaggio per ora della giornata."}


## summary statistics by HOUR of the DAY #############
### duration of the trip by hour of the day ##########


triptime_hour <- trips %>%
  group_by(month, hour, vehtype) %>%
  summarise(mean_trip_time = mean(triptime_min, na.rm = T)) 


p <- ggplot(data = triptime_hour,
              aes(hour, mean_trip_time, fill = hour)) + guides(fill=FALSE) +
    geom_bar(stat = "identity") + 
    # facet_wrap( ~ month, scales = "free_y") +
    facet_grid(month ~ vehtype, scales = "free", space = "free") +
    guides(fill=FALSE) +
    ylim(0, 50) +
    theme_bw() +
    theme( strip.text = element_text(size = 15)) +
    theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
    theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
    theme(axis.title.x = element_blank()) +                  # Remove x-axis label
    ylab("minuti") +            # Set y-axis label
    theme(axis.title.y = element_text(face="bold", colour="black", size=14),
          axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
    xlab("") +            # Set y-axis label
    theme(axis.title.x = element_text(face="bold", colour="black", size=12),
          axis.text.x  = element_text(angle=0, vjust=1, hjust=0.5, size=10)) +
    scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23)) +
    # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
    ggtitle("tempo medio di viaggio per ora della giornata") + 
    theme(plot.title = element_text(lineheight=.8, face="bold"))
p



````


*<br/><br/>*

````{r, message = FALSE, echo = FALSE, warning = FALSE, fig.width=9,fig.height=5,  fig.cap ="**Figura 9.** Tempo medio di viaggio per giorno della settimana."}


## summary statistics by DAY of the WEEK #############
### duration of the trip by day of the week ##########


triptime_weekdays <- trips %>%
  group_by(month, day, vehtype) %>%
  summarise(mean_trip_time = mean(triptime_min, na.rm = T)) 


triptime_weekdays <- as.data.frame(triptime_weekdays)
categories <- c("lunedì", "martedì", "mercoledì", "giovedì", "venerdì" ,"sabato" ,"domenica")

p <- ggplot(data = triptime_weekdays,
            aes(day, mean_trip_time, fill = day)) + guides(fill=FALSE) +
  geom_bar(stat="identity") +
  facet_grid(month ~ vehtype, scales = "free", space = "free") +
  guides(fill=FALSE) +
  scale_x_discrete(limits = categories) +
  # ylim(0, 20) +
  theme_bw() +
  theme( strip.text = element_text(size = 15)) +
  theme(axis.text.x=element_text(angle=0,hjust=1,vjust=0.5)) +
  theme(axis.text.x=element_text(size=11,face="bold", colour = "black")) +
  theme(axis.title.x = element_blank()) +                  # Remove x-axis label
  ylab("minuti") +            # Set y-axis label
  theme(axis.title.y = element_text(face="bold", colour="black", size=14),
        axis.text.y  = element_text(angle=0, vjust=0.5, size=14)) +
  xlab("") +            # Set y-axis label
  theme(axis.title.x = element_text(face="bold", colour="black", size=14),
        axis.text.x  = element_text(angle=45, vjust=1, size=14)) +
  # geom_text(aes(label = paste(count, sep = "")), size = 5, hjust = 0.5, vjust = -0.5) +
  # geom_hline(yintercept = 15, col="black", lty=2, size=1) +
  ggtitle("tempo medio di viaggio per giorno della settimana") + 
  theme(plot.title = element_text(lineheight=.8, face="bold"))
p


````


